#!/usr/bin/env bash
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case"
FZF_DEFAULT_COMMAND="$RG_PREFIX ''" \
    fzf --ansi --disabled \
    --bind "change:reload:$RG_PREFIX {q} || true" \
    --delimiter ':' \
    --preview 'batcat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    --bind 'enter:become(nvim {1} +{2})'
